### PR TITLE
Bootswatch Theme select

### PR DESCRIPTION
**Pull request by rjsachse**
change theme to a bootswatch theme, auto resize of buttons, all
readable, all themes work

### CODE REVIEW

**Comment by sidoh** [comment]
Thanks @rjsachse.  I apologize for the slow response time here.  I should have a chance to look this weekend.

**Comment by sidoh** [comment]
Looks great, thank you!

I'm going to pull master and regenerate the web artifacts?  I merged the favicon PR, so there are conflicts.  After that, will be happy to merge.

**Comment by rjsachse** [comment]
ok yes no worry

**Comment by rjsachse** [comment]
should be good to go now

**Comment by sidoh** [comment]
Excellent.  Thank you!

**Pull request merged**
