### PR TITLE
Add uniq_id to MQTT Discovery message

### PR DESCRIPTION
**Pull request by nordeep**
Generate uniq_id from ESP ChipID and alias
Closing #607

### CODE REVIEW

**Comment by clau-bucur** [comment]
Hi @nordeep. I think it should be **`config[F("unique_id")]`**, please double check.

**Comment by nordeep** [comment]
> Hi @nordeep. I think it should be **`config[F("unique_id")]`**, please double check.

`uniq_id ` is abbreviations of `unique_id` which allowed to use to minimize discovery payload - https://www.home-assistant.io/docs/mqtt/discovery/

**Comment by clau-bucur** [comment]
Sorry then :D, thanks for the explanation

**Comment by sidoh** [comment]
Thank you!

**Pull request merged**
