### PR TITLE
Adding some function

### PR DESCRIPTION
**Pull request by destiny86bln**
Adding i2c Sensors
- SI7021 > Humidity and Temperature
- BH1750 > ambient light intensity
- BME280 > Temperature, barometric Pressure and Humidity
- BMP280 > Temperature and barometric Pressure

Added 4 Pins 
Pipeing State -> Digital IN -> MQTT

Pushing MQTT Sensordata once a minute
Pushing MQTT Pin state change

Added OTA Service
Added Static IP and own Hostname

GUI Sub Headlines and some more Settings

### CODE REVIEW

**Comment by sidoh** [comment]
Happy to hear out what you have in mind, but I would prefer to keep this project pretty tightly scoped (e.g., no responsibility beyond controlling and exposing interfaces to control Milight devices).

**Comment by destiny86bln** [comment]
Yes it is really a great project.
My MQTT server accepts only certain client ids to connect. Therefore the configable client ID in the settings.
I use it in conjunction with Home Assistant. Therefore for me it is usefull to collect additional data such as temperature ,humidity and pressure. 
Maybe there is a way to seperate additional features from the main core somehow?

**Comment by bombcheck** [comment]
+1 for static IP and own Hostname.

**Comment by sidoh** [comment]
Configurable hostname and static IP should definitely be features.

I think the sensor functionality should probably not be in this project, though.

It may be possible to extract core functionality into a library, but that'd be a pretty big undertaking.

**Comment by bombcheck** [comment]
Correct, we should not load to much "intelligence" into a "simple" hub.

**Comment by sidoh** [comment]
@destiny86bln - I should've mentioned this from the get-go, but I super appreciate the contributions and suggestions.  Thanks for taking the time to put this together.

How are you thinking about this PR?  Are there major changes you'd want to make before you feel it's ready?  Do my comments resonate with you?

Of the changes you've added, I'd feel great about:

* Configurable static IP and hostname
* Improved (working?) Windows build pipeline
* More segmented settings

While the others are super cool, I feel like they're beyond the scope of this project.

**Comment by destiny86bln** [comment]
@sidoh - yes i m building some GUI things right now 
screenshot to take a first look 
its for add , delete, edit the devices
an give them clear names 
what do u think?

screenshot-2017-11-9 milight hub

**Comment by sidoh** [comment]
Much more organized!  Love where it's heading.

**Pull request closed without merging**
