### PR TITLE
Improve pinout documentation in README.md

### PR DESCRIPTION
**Pull request by saerdnaer**
see commit

### CODE REVIEW

**Comment by saerdnaer** [comment]
I'm not really sure, is that column should be dropped or not. When I clicked the link yesterday, the images did not load and my browser did not jump to the right place, for an unknown reason.  I only realised this after I already head connected the two modules without the photo. But it helped debugging my errors with photo afterwards (I switched MOSI and MISO). So we could rename the column from 'comment' to 'recommended color', if you want...

**Comment by sidoh** [comment]
The colors are arbitrary, right?  This isn't some SPI convention is it?

If they're arbitrary, I think it's only helpful if accompanied with an image.  Otherwise it seems extraneous.  Maybe we can add an image?

**Comment by saerdnaer** [comment]
Red and black are quite common for +5V and ground, the others are probably the default order when connecting a classic ribbon cable (aka "Row Dupont Cable") to a NRF24L01+:

image
(red to grey are still connected)

**Comment by saerdnaer** [comment]
According to "Henrik Ekblad - Founder MySensors.org/OpenHardware.io" we can use https://www.mysensors.org/uploads/57c1a7461730a6c715b6b1b5/image/connect_nodemcu.png
https://www.mysensors.org/uploads/57c1a2411730a6c715b6b1b0/image/nrfTop.png 
– I will update the PR, when I have time for that. In which folder should we put the images? A new "docs" folder?

**Comment by saerdnaer** [comment]
nrftop
connect_nodemcu

**Comment by sidoh** [comment]
Could we also add a source for the images?  Other than that, LGTM.

**Comment by sidoh** [comment]
@saerdnaer are you able to add sources for the images?  Will be happy to merge after that.  Apologize for the several rounds of back and forth.

**Comment by saerdnaer** [comment]
What do you mean with "sources" the URLs are inside of https://github.com/sidoh/esp8266_milight_hub/pull/339#issuecomment-424005652 – please implemented the remaining changes yourself.

**Comment by sidoh** [comment]
Sure.  I meant attribution.  Don't want the images linked to break, but they should be attributed to the person/website that created them.

**Comment by sidoh** [comment]
Thank you!  Realized that since this PR has been open, the default pin for CE was changed from GPIO16 to GPIO4.  I'm going to merge this into a branch and make that edit before merging into master.

Appreciate the effort, and thanks for your patience with the super long iterations.

**Pull request merged**
