### PR TITLE
add a global mqtt debounce delay

### LINKED ISSUE #615: Add option to debounce MQTT state updates
### Describe the bug

When I send a command over MQTT with multiple changes (for example hue and level), multiple status messages get sent, with the parameters changing one by one. That means, when I change both level and hue, the level gets changed first and a status message is sent with the old hue and just after that the full new status is sent. This is a problem, because it leads to jumping values in my control dashboard, as the old hue gets pushed as a update after I changed it with a command.

### Steps to reproduce

send MQTT 1: {"state":"ON","level":95,"hue":250}
send MQTT 2: {"state":"ON","level":90,"hue":240}

received status messages after MQTT 2:
1: {"state":"ON","level":95,"hue":250,"saturation":100,"bulb_mode":"color"}
2: {"state":"ON","level":90,"hue":240,"saturation":100,"bulb_mode":"color"}

### Expected behavior

Don't send status message 1 and send only 2 (only the full status update)

expected message after MQTT send 2:
{"state":"ON","level":90,"hue":240,"saturation":100,"bulb_mode":"color"}

### Setup information

MQTT messages normally sent with Openhab, but also tested with MQTT.fx client.

#### Firmware version

1.10.5 (d1_mini)

#### Output of http://milight-hub.local/about

```json
{"firmware":"milight-hub","version":"1.10.5","ip_address":"192.168.1.2","reset_reason":"External System","variant":"d1_mini","free_heap":17704,"arduino_version":"2_4_2","queue_stats":{"length":0,"dropped_packets":0}}
```

#### Output of http://milight-hub.local/settings

```json
{"admin_username":"","admin_password":"","ce_pin":4,"csn_pin":15,"reset_pin":0,"led_pin":-2,"radio_interface_type":"nRF24","packet_repeats":50,"http_repeat_factor":1,"auto_restart_period":0,"mqtt_server":"192.168.1.141:1883","mqtt_username":"****","mqtt_password":"****","mqtt_topic_pattern":"milight/commands/:device_id/:device_type/:group_id","mqtt_update_topic_pattern":"","mqtt_state_topic_pattern":"milight/states/:device_id/:device_type/:group_id","mqtt_client_status_topic":"","simple_mqtt_client_status":false,"discovery_port":48899,"listen_repeats":0,"state_flush_interval":10000,"mqtt_state_rate_limit":500,"packet_repeat_throttle_sensitivity":0,"packet_repeat_throttle_threshold":200,"packet_repeat_minimum":3,"enable_automatic_mode_switching":false,"led_mode_wifi_config":"Fast toggle","led_mode_wifi_failed":"Fast blip","led_mode_operating":"On","led_mode_packet":"Flicker","led_mode_packet_count":3,"hostname":"milight-hub","rf24_power_level":"MAX","rf24_listen_channel":"LOW","wifi_static_ip":"","wifi_static_ip_gateway":"","wifi_static_ip_netmask":"","packet_repeats_per_loop":10,"home_assistant_discovery_prefix":"","wifi_mode":"n","default_transition_period":500,"rf24_channels":["LOW","MID","HIGH"],"device_ids":[0,1,2],"gateway_configs":[],"group_state_fields":["state","level","hue","saturation","mode","color_temp","bulb_mode"],"group_id_aliases":{"Terrasse Hinten":["rgb_cct",0,1]}}
```

### PR DESCRIPTION
**Pull request by annego15**
I added a global debounce delay for MQTT state updates. You can change that setting in the web configurator. This prevents MQTT state updates to be sent while new packets are still being sent. This should fix #615.

### CODE REVIEW

**Comment by sidoh** [comment]
Hey @annego15, this is awesome!  Appreciate you working on this.

I'll give this a try over the weekend.

I'd like to add a test for it as well.  If you're feeling extra adventurous, the test suite is here:

https://github.com/sidoh/esp8266_milight_hub/tree/master/test/remote

relevant test is probably `mqtt_spec.rb`.

(don't run this against your real ESP -- it'll wipe the settings)

**Comment by annego15** [comment]
I tried to add a test, but that is way to complicated for me as I have absolutely zero experience in doing such tests.

**Comment by arcangel321** [comment]
I got the same issue any News when this wil be implemented in the new version?

**Comment by sidoh** [comment]
Sounds good, I'll take a look at adding a test this weekend, @annego15.  Could you grant me access to your fork (just the `debounce-delay` branch is fine)?

**Comment by annego15** [comment]
I gave you access, thank you for taking a look.

**Comment by sidoh** [comment]
Added some tests.  They pass!

Unfortunately, one of the UDP tests fails transiently (roughly 50% of the time) with this change.  It did not fail once after 10 tries on 1.10.5:

```
  1) UDP servers on/off commands should result in an MQTT update
     Failure/Error:
       @client.get(topic) do |topic, message|
         ret_val = yield(topic, message)
         raise BreakListenLoopError if ret_val
       end

     Timeout::Error:
       execution expired
     # ./lib/mqtt_client.rb:77:in `block (2 levels) in on_message'
     # ./lib/mqtt_client.rb:76:in `block in on_message'
```

It appears that the state update here is getting swallowed.

**Pull request merged**
