### PR TITLE
Modified to work with Adafruit Feather Huzzah

### PR DESCRIPTION
**Pull request by hastarin**
This turned out to be exceptionally easy.  Thanks for all your work here!

### CODE REVIEW

**Comment by hastarin** [comment]
Actually I'll need to do more work it seems.

Things work fine to start but then I just get an error until I reset the board.

> ERROR: packet buffer full!  Cannot buffer a new packet.  THIS IS A BUG!

**Comment by hastarin** [comment]
So it turns out that is an existing issue.  #170 

I'll have to see if I can find the time to investigate if there is anything I can do to help out there.

**Comment by sidoh** [comment]
Is this with the "CCT" remote type?  I think we just need to increase the size of the buffer here:

https://github.com/sidoh/esp8266_milight_hub/blob/master/lib/MiLight/PacketFormatter.h#L12-L15

Would be nice to know why 140 bytes is wrong, though.  I can't think of a reason more than 140 bytes would be necessary.  Could just be a silly off-by-one error in the bounds checking:

https://github.com/sidoh/esp8266_milight_hub/blob/master/lib/MiLight/PacketFormatter.cpp#L119-L123

Anyway, PR looks great, and as long as you're using the CCT remote type, I think the error you're seeing is unrelated.

**Comment by hastarin** [comment]
@sidoh Yes this is with the CCT remote type.  I've just confirmed it's with the brightness command.

I'll look into it today.  

From my days of controlling these things via Tasker and my UDP Sender app I know the UDP commands for full brightness were to send the turn on twice with 120ms delay between them.

So, aside from the "ouch it's too bright" factor, one option may be to send the command to go full brightness, if I can figure out how to do that, and then ramp down.

**Comment by hastarin** [comment]
I've confirmed the Color Temperature causes this too.   I'm currently just experimenting with the built in UI and trying to relearn C++ since it's been 20 years since I touched it.

I noticed the light seems to go through 2 ramps of down/up instead of one.  So I've currently just doubled the buffer size to see if that helps and been unable to trigger the bug since.

Now to try and figure out why the double ramp, and what I can do to prevent it, or change the behavior to be a bit smarter about moving states.

I do wonder if having a "resync" option would be of more use than trying to do this on every change?

**Comment by sidoh** [comment]
Thanks for digging into that!  Odd that it's doing two cycles -- that certainly shouldn't be happening.  I'll drop some notes in the the issue you found (#170).  As this PR is unrelated, let's continue the discussion on this bug there.

A thought on the PR -- is 1MB flash (with 64KB SPIFFS) enough to support OTA updates?  If not, we should probably document that somehow.

**Comment by hastarin** [comment]
I honestly have no idea on the OTA updates.  From what I can tell the board I'm using has 4MB flash:
https://learn.adafruit.com/adafruit-feather-huzzah-esp8266

**Comment by sidoh** [comment]
Ah ok.  Asking because of the build flag:

```
-Wl,-Tesp8266.flash.1m64.ld
```

Which assumes the chip has 1MB of flash.  Does it work without this flag?

**Comment by hastarin** [comment]
Sorry that's me copy/pasting and not knowing what I'm doing.

Should I be using the following instead?
`
-Wl,-Tesp8266.flash.4m1m.ld
`

Or just remove it entirely?

It does work without it.  I lost my settings, but I guess they were stored at a different offset.  Saving things again still survived a reset.

**Comment by sidoh** [comment]
Gotcha.  Probably best to remove it if it works.  Think it gets auto-assigned without it, and it's usually the right thing.

**Comment by hastarin** [comment]
All done.

**Comment by sidoh** [comment]
Awesome.  Thanks, @hastarin!

**Pull request merged**
