### PR TITLE
Use single topic for MQTT client status (LWT, birth, etc.)

### PR DESCRIPTION
**Pull request by sidoh**
As suggested/discussed in this comment thread: https://github.com/sidoh/esp8266_milight_hub/issues/418#issuecomment-482675232

Thanks, @rejoe2!

### CODE REVIEW

**Comment by odis68** [comment]
Tell me how to useLWT. Because messages must be 2. The first is entered into the broker when connected with an indication of the topic, and the second is periodically sent to the broker for a status condition. Is it possible to use a separate topic (milight/states/LWT) for LWT or should it be combined with any of the other topics?

**Comment by odis68** [comment]
image

**Comment by rejoe2** [comment]
Are you using latest version (1.9.0-rc3)?

**Comment by odis68** [comment]
Sorry for an example from another project. This is not disrespectful but for example only.
image

Yes, I have installed latest version (1.9.0-rc3)

**Comment by sidoh** [comment]
@odis68, the name of the setting changed.  It's now `mqtt_client_status_topic`.  You'll need to reconfigure it.

**Comment by sidoh** [comment]
Guessing the data on your `status/LWT` topic is a left over retained message.

**Comment by odis68** [comment]
image

**Comment by sidoh** [comment]
That is not RC3.  Looks like RC2 or earlier.  RC3 here:

https://github.com/sidoh/esp8266_milight_hub/releases/tag/1.9.0-rc3

**Comment by odis68** [comment]
r. RC3 
I cleared the topic () by entering an empty value but after resetting the same value.

**Comment by sidoh** [comment]
The UI is definitely from RC2.

Can you maybe try force-refreshing?  Perhaps the UI got cached by the browser or something.

**Comment by odis68** [comment]
You were right!!! The problem in the browser helped clear the cache !! Thank you very much you have fulfilled several trials at once.

**Pull request merged**
